name: Book A DJ
favicon: null
layout_spectrum: 0.0525761682074517
typography_spectrum: 0.9936161988880485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7408686974085867
  lightness: 0.978896044427529
  saturation: 0.4433236261829734
  rhythmicContrast: 0.21348995435982943
purpose: []
